### ISSUE TITLE
Revising homepage by content type

### ISSUE THREAD

**Issue by ragozzine** [jnjosh/internet-weblog#13]
Hi - great theme!

Any advice on how to best revise the homepage so that I have the 5 most recent items from each content type, rather than everything in a single content river?

**Comment by ragozzine** [comment]
I have a new idea - thanks!

**Comment by jnjosh** [comment]
Ah sorry for the delay in response. Thanks for using the theme and let me know if there is anything I can change (or if you want to propose a change via PR, that's fine too).
