### ISSUE TITLE
Partially ported to Zola

### ISSUE THREAD

**Issue by ghlecl** [jnjosh/internet-weblog#14]
Hi,

I have looked into switching my static site generator to [Zola](https://www.getzola.org/).  Because I like your theme so much, I have partially (as in only the parts I needed) "ported" it to Zola.  I put quotes there because I haven't actually made it a seperate theme usable by other people: I just used your formatting and CSS and adapted the templates to use the Zola templating engine.

I want to give you credit since I basically just copied your things.  The way I did it is to put a link to your personal website and to this git repo in the footer of my site.   Is that OK/enough to comply with the MIT license (it requires attribution if I understand correctly and I might be wrong)?  Would that be OK with you?  Here is what it would look like:

<img width="365" alt="Screen Shot 2022-04-21 at 22 21 40" src="https://user-images.githubusercontent.com/8061814/164585747-3b388e4f-6a60-4748-b41c-5817cc099d3a.png">
<img width="811" alt="Screen Shot 2022-04-21 at 22 21 48" src="https://user-images.githubusercontent.com/8061814/164585787-5ed2f166-19aa-4f4c-a401-ec5cd16afa30.png">

I am almost done and would be ready to publish soon, but I would rather make sure you're OK with it before I do.  Thanks in any case.

PS: Did not find a way other than an issue to ask.  Hope it's OK.

**Comment by jnjosh** [comment]
Hey!

Yeah that's totally fine and ok! I haven't heard of Zola yet either—maybe I'll take a look. It's been awhile since I made a theme anyway :) 

Josh
