### ISSUE TITLE
Hugo deprecation warning for Page.Now()

### ISSUE THREAD

**Issue by ritesh** [jnjosh/internet-weblog#4]
First of all, thanks for the amazing theme! I've just discovered that hugo v0.21 deprecates using the Page's Now function in favour of the template now function.  This does not break the theme just yet, but subsequent versions of hugo will not support this. 

I could find only one instance of using the page's now function in page_footer.html:20. The fix is pretty straightforward `{{ .Now.Format "2006" }}` to `{{ now.Year }}`.  Let me know if you want me to submit a pull request.

**Comment by jnjosh** [comment]
Fixed with #6.

Thanks for the issue and sorry for the long delay!
