### ISSUE TITLE
Microposts only

### ISSUE THREAD

**Issue by Fastidious** [jnjosh/internet-weblog#8]
I like your theme, thank you!

I am using it to post `microposts` only. Is there a way to separate how `microposts` look while in a list, and how they look while showing a single one? It seems the code is being re-used as it is, so making text bigger, for example, on a single one, will also affect the text size for `microposts` in list view.

**Comment by jnjosh** [comment]
Sorry for the delay! 

I just pushed this commit: 675b6b6f8. I think this will allow you to, with custom css, differentiate between when it's displaying in a list and when it's displaying single. 

For example, after updating the theme on my site, I added this to my css:

```
.content .micropost > p {
  color: #ff0000;
  font-size: 28px;
  line-height: 48px;
  margin: 0;
  text-align: justify;
}

.list .micropost > p {
  color: #666666;
  font-size: 18px;
  line-height: 28px;
  margin: 0;
  text-align: justify;
}
```

Now it displays normally on a list and huge and red on the single page. Is that what you are looking for?

**Comment by Fastidious** [comment]
That does it! How will I go to show it like that on desktop, but how it was before while on mobile? Thanks for the help!

**Comment by jnjosh** [comment]
I think you'd have to have a css media query for mobile sizes. I'm not a css expert so there could be a better way. 

```
@media screen
and (max-width: 780px) {

    .list .micropost > p, .content .micropost > p {
      color: #666666;
      font-size: 18px;
      line-height: 28px;
      margin: 0;
      text-align: justify;
    }

}
```
